# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ua.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ua.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x08ua.proto\";\n\tUAProduct\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"C\n\x06UAPack\x12\r\n\x05whnum\x18\x01 \x02(\x05\x12\x1a\n\x06things\x18\x02 \x03(\x0b\x32\n.UAProduct\x12\x0e\n\x06shipid\x18\x03 \x02(\x03\"S\n\rUAShipRequest\x12\x18\n\x07package\x18\x01 \x02(\x0b\x32\x07.UAPack\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\x12\x12\n\nupsAccount\x18\x04 \x01(\t\"?\n\rUATruckArrive\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\r\n\x05whnum\x18\x02 \x02(\x05\x12\x0e\n\x06shipid\x18\x03 \x02(\x03\"c\n\x0e\x41mazonCommands\x12 \n\x08req_ship\x18\x01 \x01(\x0b\x32\x0e.UAShipRequest\x12\x1b\n\x13req_deliver_truckid\x18\x02 \x01(\x05\x12\x12\n\ndisconnect\x18\x03 \x01(\x08\"2\n\x0cUPSResponses\x12\"\n\nresp_truck\x18\x01 \x01(\x0b\x32\x0e.UATruckArrive')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UAPRODUCT = _descriptor.Descriptor(
  name='UAProduct',
  full_name='UAProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UAProduct.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='UAProduct.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='UAProduct.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=71,
)


_UAPACK = _descriptor.Descriptor(
  name='UAPack',
  full_name='UAPack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whnum', full_name='UAPack.whnum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='things', full_name='UAPack.things', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shipid', full_name='UAPack.shipid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=140,
)


_UASHIPREQUEST = _descriptor.Descriptor(
  name='UAShipRequest',
  full_name='UAShipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='UAShipRequest.package', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='UAShipRequest.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='UAShipRequest.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upsAccount', full_name='UAShipRequest.upsAccount', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=225,
)


_UATRUCKARRIVE = _descriptor.Descriptor(
  name='UATruckArrive',
  full_name='UATruckArrive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UATruckArrive.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='whnum', full_name='UATruckArrive.whnum', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shipid', full_name='UATruckArrive.shipid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=290,
)


_AMAZONCOMMANDS = _descriptor.Descriptor(
  name='AmazonCommands',
  full_name='AmazonCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_ship', full_name='AmazonCommands.req_ship', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_deliver_truckid', full_name='AmazonCommands.req_deliver_truckid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='AmazonCommands.disconnect', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=391,
)


_UPSRESPONSES = _descriptor.Descriptor(
  name='UPSResponses',
  full_name='UPSResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp_truck', full_name='UPSResponses.resp_truck', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=443,
)

_UAPACK.fields_by_name['things'].message_type = _UAPRODUCT
_UASHIPREQUEST.fields_by_name['package'].message_type = _UAPACK
_AMAZONCOMMANDS.fields_by_name['req_ship'].message_type = _UASHIPREQUEST
_UPSRESPONSES.fields_by_name['resp_truck'].message_type = _UATRUCKARRIVE
DESCRIPTOR.message_types_by_name['UAProduct'] = _UAPRODUCT
DESCRIPTOR.message_types_by_name['UAPack'] = _UAPACK
DESCRIPTOR.message_types_by_name['UAShipRequest'] = _UASHIPREQUEST
DESCRIPTOR.message_types_by_name['UATruckArrive'] = _UATRUCKARRIVE
DESCRIPTOR.message_types_by_name['AmazonCommands'] = _AMAZONCOMMANDS
DESCRIPTOR.message_types_by_name['UPSResponses'] = _UPSRESPONSES

UAProduct = _reflection.GeneratedProtocolMessageType('UAProduct', (_message.Message,), dict(
  DESCRIPTOR = _UAPRODUCT,
  __module__ = 'ua_pb2'
  # @@protoc_insertion_point(class_scope:UAProduct)
  ))
_sym_db.RegisterMessage(UAProduct)

UAPack = _reflection.GeneratedProtocolMessageType('UAPack', (_message.Message,), dict(
  DESCRIPTOR = _UAPACK,
  __module__ = 'ua_pb2'
  # @@protoc_insertion_point(class_scope:UAPack)
  ))
_sym_db.RegisterMessage(UAPack)

UAShipRequest = _reflection.GeneratedProtocolMessageType('UAShipRequest', (_message.Message,), dict(
  DESCRIPTOR = _UASHIPREQUEST,
  __module__ = 'ua_pb2'
  # @@protoc_insertion_point(class_scope:UAShipRequest)
  ))
_sym_db.RegisterMessage(UAShipRequest)

UATruckArrive = _reflection.GeneratedProtocolMessageType('UATruckArrive', (_message.Message,), dict(
  DESCRIPTOR = _UATRUCKARRIVE,
  __module__ = 'ua_pb2'
  # @@protoc_insertion_point(class_scope:UATruckArrive)
  ))
_sym_db.RegisterMessage(UATruckArrive)

AmazonCommands = _reflection.GeneratedProtocolMessageType('AmazonCommands', (_message.Message,), dict(
  DESCRIPTOR = _AMAZONCOMMANDS,
  __module__ = 'ua_pb2'
  # @@protoc_insertion_point(class_scope:AmazonCommands)
  ))
_sym_db.RegisterMessage(AmazonCommands)

UPSResponses = _reflection.GeneratedProtocolMessageType('UPSResponses', (_message.Message,), dict(
  DESCRIPTOR = _UPSRESPONSES,
  __module__ = 'ua_pb2'
  # @@protoc_insertion_point(class_scope:UPSResponses)
  ))
_sym_db.RegisterMessage(UPSResponses)


# @@protoc_insertion_point(module_scope)
