# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazontransaction',
            name='items_detail',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
