# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20170425_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazonAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
