# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170425_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amazontransaction',
            name='amazonAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.AmazonAccount'),
        ),
    ]
