# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20170425_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='assigned_trunk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracking',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
