# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20170426_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
