# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_amountbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountbalance',
            name='user',
        ),
        migrations.DeleteModel(
            name='AmountBalance',
        ),
    ]
