# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0014_auto_20170428_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazontransaction',
            name='user',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazontransactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
