# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_amazontransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazontransaction',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
