# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_amazontransaction_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='amazonTransaction',
        ),
        migrations.AddField(
            model_name='amazontransaction',
            name='tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazontransactions', to='apps.Tracking'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='tracking_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amazontransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazontransactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
