# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20170428_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazontransaction',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazontransactions', to='apps.Tracking'),
        ),
    ]
