# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20170428_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='warehouse_id',
            field=models.IntegerField(default=0),
        ),
    ]
