# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0019_tracking_warehouse_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazontransaction',
            old_name='transaction_id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='amazontransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='tracking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to=settings.AUTH_USER_MODEL),
        ),
    ]
