# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20170429_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazontransaction',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
