# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auto_20170429_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trunk',
            name='last_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trunk',
            name='last_y',
            field=models.IntegerField(default=0),
        ),
    ]
