# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_auto_20170429_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='trunk',
        ),
        migrations.AddField(
            model_name='tracking',
            name='trunk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
