# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_auto_20170429_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='trunk',
            name='tracking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
