# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_trunk_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=5)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
